apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: ntfy
  # https://codeberg.org/wrenix/helm-charts/src/branch/main/ntfy/values.yaml
  values:
    image:
      repository: binwiederhier/ntfy
      pullPolicy: IfNotPresent

    kubectl:
      # -- image needed for setup (store generated VAPID / WebPush keys)
      image:
        registry: docker.io
        repository: bitnami/kubectl
        pullPolicy: IfNotPresent
        tag: 1.32.2

    updateStrategy:
      type: Recreate

    ntfy:
      baseURL: https://ntfy.catboy.rest
      listen:
        http: :8080
      cache:
        file: /data/cache.db
        duration: 12h
      auth:
        file: /data/auth.db
        defaultAccess: deny-all
      attachment:
        cacheDir: /data/attachment.db
        sizeLimit:
          total: 5G
          file: 50M
        expireDuration: 24h
      keepaliveInterval: 45s
      managerInterval: 1m
      webRoot: app
      enableReservations: true
      enableSignup: false
      enableLogin: true
      upstreamBaseURL: https://ntfy.sh
      globalTopicLimit: 100
      behindProxy: true

    ## Enable persistence using Persistent Volume Claims
    persistence:
      enabled: true
      storageClass: zfs-local-dataset
      accessMode: ReadWriteOnce
      size: 25Gi

    env: []
    envFrom: []

    # -- set securityContext on container level
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000

    podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: Always

    service:
      http:
        type: ClusterIP
        port: 8080

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - host: ntfy.catboy.rest
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - ntfy.catboy.rest
        secretName: ntfy-letsencrypt-cert

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
      memory: 128Mi

    autoscaling:
      enabled: false