apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: ntfy
  # https://codeberg.org/wrenix/helm-charts/src/branch/main/ntfy/values.yaml
  values:
    image:
      repository: binwiederhier/ntfy
      pullPolicy: IfNotPresent

    kubectl:
      # -- image needed for setup (store generated VAPID / WebPush keys)
      image:
        registry: docker.io
        repository: bitnami/kubectl
        pullPolicy: IfNotPresent
        tag: 1.32.2

    updateStrategy:
      type: Recreate

    ntfy:
      baseURL: https://ntfy.catboy.rest
      listen:
        http: :80
      auth:
        defaultAccess: deny-all
      keepaliveInterval: "45s"
      managerInterval: "1m"
      webRoot: app
      enableReservations: true
      enableSignup: false
      enableLogin: true
      upstreamBaseURL: "https://ntfy.sh"
      webPush:
        keys:
          create: false
          public:
          private:
        file: "/data/webpush.db"
        emailAddress: ""
      globalTopicLimit: 100
      behindProxy: true
      # NTFY_STRIPE_SECRET_KEY
      # NTFY_STRIPE_WEBHOOK_KEY
      # NTFY_BILLING_CONTACT
      # metrics:
        # enable: true
        # port: 9000

    ## Enable persistence using Persistent Volume Claims
    persistence:
      enabled: true
      storageClass: zfs-local-dataset
      accessMode: ReadWriteOnce
      size: 1Gi

    env: []
    envFrom: []

    # -- set securityContext on container level
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

    service:
      http:
        type: ClusterIP
        port: 80

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - host: ntfy.catboy.rest
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - ntfy.catboy.rest
        secretName: ntfy-letsencrypt-cert

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
      memory: 128Mi

    autoscaling:
      enabled: false