apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
spec:
  encryptedData:
    token: AgCDL6w++oKrMPTNQl0g3nEq6lNpe0q1/Iva/Qm0Bntfw9Ft4tF8AEfWyP+uG8YEZFgg87UkMyy0vVdGi+oIKuruoIBY7dHEYVZN84gTqS2rCS+0gWJ+3Zn9zON6P/2UzSFLIck1AuxJvkRwx4hiJzvBIzmFx6XyI43JQPoLEYShgC6Yx9XrkeI4lyGKn5aVXhfE0T2P7QPqpUXlF6E99RRF/4T151YW+RtIhRKpguJVZ+nfcUxKtGvvJyW6UxGJkOLhynbE15niUH+32uvIrihGj17BPn+1du6hvdrsn7XjpAEdbca0/eCGqC8xoSZ8GhMR8qrBu/gOBARttqVXKiRbdr0ZwecWZ0YdxeqCqlYjFj0INhIkfWtG1gK84Da6xFTvdk0ygHCaxQcPrzfddNz6LVKS/AKVUQEYqpITc3eMtV32qiNeOzfftTudpuM1/BuL34Tq2+6O6MkPkTJ2MKA71LzdLaOUpwbi6HP+TDGckMOa4iVgHjx8pfN1enUaavUGjVqg+Cs3yK+biWhrGH1mkQoCF0AhnUXXpmdpZKlKYZHXQtYiF+Ek1sGxMu7XOz4dmQDtALcTCF50jWMqu5c6M8dgon7ElhQ8OoKTzsdzr+pm9KpUu0nAc4OoFzZbmg7+xD5mh8JDHVX5pqcRtXjTKxIUiN5PxHvLrH/IghisdkbYf0bRxLgQfkQPCnjFkbQLsMQgKWP4H5tVFkQMJpi2FpRYw3qYuKOkjO/ER3M6EiNcUe/D8uMw
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
    type: Opaque
