apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-world-data
spec:
  storageClassName: zfs-local-dataset
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-base
spec:
  storageClassName: zfs-local-dataset
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi