apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valheim
spec:
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      # Number of retries that should be attempted on failures before bailing, a negative integer equals to unlimited retries
      retries: -1
  chart:
    spec:
      chart: valheim-k8s
      version: "2.x.x"
      sourceRef:
        kind: HelmRepository
        name: valheim-repo
      interval: 12h
  # https://github.com/Addyvan/valheim-k8s/blob/main/chart/values.yaml
  values:
    worldName: cozy-lab
    serverName: CozyLab
    password: Headpats&Sake

    storage:
      pvc:
        size: 10Gi
        storageClassName: zfs-local-dataset

    serverStorage:
      pvc:
        size: 5Gi
        storageClassName: zfs-local-dataset

    networking:
      serviceType: LoadBalancer
      gamePort: 2456
      publishQueryPort: true
      nodePort: 30373

    # extraEnvironmentVars:
    #   BACKUPS: true
    #   BACKUPS_CRON: "0 * * * *"
    #   BACKUPS_MAX_AGE: 3
    #   POST_BACKUP_HOOK: "timeout 300 scp -i /extraVolumes/backup-ssh-key/ssh-privatekey -o StrictHostKeyChecking=no @BACKUP_FILE@ myself@example.com:~/valheim_backups/$(basename @BACKUP_FILE@)"