apiVersion: agones.dev/v1
kind: GameServer
metadata:
  name: ats
spec:
  ports:
  - name: game
    # [Stage:Alpha]
    # [FeatureFlag:PortRanges]
    # range is the optional port range name from which to select a port when using a 'Dynamic' or 'Passthrough' port policy.
    range: default
    # portPolicy has four options:
    # - "Dynamic" (default) the system allocates a free hostPort for the gameserver, for game clients to connect to
    # - "Static", user defines the hostPort that the game client will connect to. Then onus is on the user to ensure that the
    # port is available. When static is the policy specified, `hostPort` is required to be populated
    # - "Passthrough" dynamically sets the `containerPort` to the same value as the dynamically selected hostPort.
    #      This will mean that users will need to lookup what port has been opened through the server side SDK.
    # - "None" means the `hostPort` is ignored and if defined, the `containerPort` (optional) is used to set the port on the GameServer instance.
    portPolicy: Static
    # The name of the container to open the port on. Defaults to the game server container if omitted or empty.
    container: ats
    # the port that is being opened on the game server process
    containerPort: 27015
    # the port exposed on the host, only required when `portPolicy` is "Static". Overwritten when portPolicy is "Dynamic".
    hostPort: 27015
    # protocol being used. Defaults to UDP. TCP and TCPUDP are other options
    # - "UDP" (default) use the UDP protocol
    # - "TCP", use the TCP protocol
    # - "TCPUDP", uses both TCP and UDP, and exposes the same hostPort for both protocols.
    #       This will mean that it adds an extra port, and the first port is set to TCP, and second port set to UDP
    protocol: TCPUDP
  - name: query
    range: default
    portPolicy: Static
    container: ats
    containerPort: 27016
    hostPort: 27016
    protocol: TCPUDP
  health:
    disabled: true
  template:
    metadata:
      labels:
        game: ats
    spec:
      containers:
      - name: ats
        image: lshallo/ats-convoy-server:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2500m # 2.5 cpu cores
            memory: 4Gi
          limits:
            cpu: 2500m # 2.5 cpu cores
            memory: 4Gi
        env:
        - name: ETS_SERVER_WRITE_CONFIG
          value: 'true'
        - name: ETS_SERVER_SHOW_SERVER
          value: 'true'
        - name: ETS_SERVER_UPDATE_ON_START
          value: 'true'
        - name: ETS_SERVER_NAME
          value: '1tr'
        - name: ETS_SERVER_DESCRIPTION
          value: "1tr"
        - name: ETS_SERVER_WELCOME_MESSAGE
          value: "1tr"
        - name: ETS_SERVER_MAX_PLAYERS
          value: '8'
        - name: ETS_SERVER_PORT
          value: '27015'
        - name: ETS_SERVER_QUERY_PORT
          value: '27016'
        - name: ETS_SERVER_MODS_OPTIONING
          value: 'true'
        - name: ETS_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ats
              key: server-password
        - name: ETS_SERVER_LOGON_TOKEN
          valueFrom:
            secretKeyRef:
              name: ats
              key: steam-login-token
