apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ats-game-udp
spec:
  entryPoints:
  - steam-game-udp
  routes:
  - services:
    - name: ats
      port: 27015
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ats-query-udp
spec:
  entryPoints:
  - steam-query-udp
  routes:
  - services:
    - name: ats
      port: 27016
