apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ats-game-tcp
spec:
  entryPoints:
  - steam-game-tcp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: ats
      port: 27015
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ats-query-tcp
spec:
  entryPoints:
  - steam-query-tcp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: ats
      port: 27016
