apiVersion: v1
kind: Service
metadata:
  name: ats
spec:
  type: ClusterIP
  ports:
  - name: game-tcp
    port: 27015
    targetPort: 27015
    protocol: TCP
  - name: game-udp
    port: 27015
    targetPort: 27015
    protocol: UDP
  - name: query-tcp
    port: 27016
    targetPort: 27016
    protocol: TCP
  - name: query-udp
    port: 27016
    targetPort: 27016
    protocol: UDP
