apiVersion: v1
kind: Service
metadata:
  name: ats
spec:
  type: NodePort
  ports:
  - name: game-tcp
    port: 27015
    targetPort: 27015
    protocol: TCP
    nodePort: 32715
  - name: game-udp
    port: 27015
    targetPort: 27015
    protocol: UDP
    nodePort: 32715
  - name: query-tcp
    port: 27016
    targetPort: 27016
    protocol: TCP
    nodePort: 32716
  - name: query-udp
    port: 27016
    targetPort: 27016
    protocol: UDP
    nodePort: 32716
