apiVersion: v1
kind: Service
metadata:
  name: ats
  annotations:
    metallb.universe.tf/address-pool: metallb-address-pool
spec:
  ports:
  - name: main
    port: 27015
    targetPort: 27015
    protocol: TCP
  - name: main-udp
    port: 27015
    targetPort: 27015
    protocol: UDP
  - name: tv
    port: 27016
    targetPort: 27016
    protocol: UDP
  - name: tv-tcp
    port: 27016
    targetPort: 27016
    protocol: TCP
  type: LoadBalancer
