apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zfs-local-dataset-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-repo
      interval: 12h
  # https://github.com/democratic-csi/democratic-csi/tree/master/examples
  values:
    # driver only works with 1.16+
    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.zfs-local-dataset"
      attachRequired: false
      storageCapacity: true
      fsGroupPolicy: File

    storageClasses:
    - name: zfs-local-dataset
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
      # distributed support is not yet ready for expansion
      allowVolumeExpansion: false
      parameters:
        fsType: zfs

    # if your cluster supports snapshots you may enable below
    # volumeSnapshotClasses: []
    #- name: zfs-local-dataset
    #  secrets:
    #    snapshotter-secret:

    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        extraArgs:
        - --leader-election=false
        - --node-deployment=true
        - --node-deployment-immediate-binding=false
        - --feature-gates=Topology=true
        - --strict-topology=true
        - --enable-capacity=true
        - --capacity-ownerref-level=1

      externalAttacher:
        enabled: false

      # distributed support is not yet ready
      externalResizer:
        enabled: false

      externalSnapshotter:
        enabled: true
        extraArgs:
        - --leader-election=false
        - --node-deployment=true

    driver:
      config:
        # please see the most up-to-date example of the corresponding config here:
        # https://github.com/democratic-csi/democratic-csi/tree/master/examples
        # YOU MUST COPY THE DATA HERE INLINE!
        driver: zfs-local-dataset
        zfs:
          datasetParentName: nvme/k8s/v
          detachedSnapshotsDatasetParentName: nvme/k8s/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetProperties:
            compression: lz4
            atime: off
            overlay: on
