apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: agones
spec:
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      # Number of retries that should be attempted on failures before bailing, a negative integer equals to unlimited retries
      retries: -1
  chart:
    spec:
      chart: agones
      version: "1.x.x"
      sourceRef:
        kind: HelmRepository
        name: agones-repo
      interval: 12h
    # https://github.com/googleforgames/agones/blob/main/install/helm/agones/values.yaml
    values:
      agones:
        controller:
          replicas: 1
        extensions:
          replicas: 1
          persistentLogsSizeLimitMB: 500
        ping:
          replicas: 1
        allocator:
          replicas: 1
