apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: "10.x.x"
      sourceRef:
        kind: HelmRepository
        name: gitea-repo
      interval: 12h
  # https://gitea.com/gitea/helm-chart/src/branch/main/values.yaml
  values:
    image:
      tag: "1.23"
      pullPolicy: IfNotPresent


    # Deployment strategy
    strategy:
      type: Recreate

    # Storage & Persistence
    persistence:
      enabled: true
      create: true
      mount: true
      size: 500Gi
      accessModes:
      - ReadWriteOnce
      storageClass: zfs-local-dataset

    # Postgres
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            password: gitea
            database: gitea
            username: gitea
      primary:
        persistence:
          size: 5Gi

    # Ingress
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - host: gitea.catboy.rest
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - gitea.catboy.rest
        secretName: gitea-cert

    # Gitea
    gitea:
      ## @param gitea.admin.username Username for the Gitea admin user
      ## @param gitea.admin.existingSecret Use an existing secret to store admin user credentials
      ## @param gitea.admin.password Password for the Gitea admin user
      ## @param gitea.admin.email Email for the Gitea admin user
      admin:
        existingSecret: gitea-creds
        email: "gitea@local.domain"

      additionalConfigSources:
      - configMap:
          name: gitea-app-ini

      metrics:
        enabled: false
        serviceMonitor:
          enabled: false

      # Either specify inline `key` and `secret` or refer to them via `existingSecret`
      ## @param gitea.oauth OAuth configuration
      oauth:
      - name: Dex
        provider: openidConnect
        existingSecret: dex-client-gitea
        autoDiscoverUrl: "https://dex.catboy.rest/.well-known/openid-configuration"
        iconUrl: "https://dexidp.io/img/logos/dex-glyph-color.png"
        scopes: email,profile,groups
        skipLocal2fa: 'true'
        requiredClaimName: groups
        groupClaimName: groups
        adminGroup: CozyDen:Admin

    # Disble HA
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
